# name: Pull Changes on Push to Develop Branch

# on:
#   push:
#     branches:
#       - develop

# jobs:
#   pull_changes:
#     if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#         with:
#           ref: develop
      
#       - name: Pull changes from develop branch
#         run: git pull origin develop
      
#       - name: Push changes to automated-docs branch
#         run: |
#           git config --global user.email "actions@github.com"
#           git config --global user.name "GitHub Actions"
#           git push origin HEAD:automated-docs
